### ISSUE TITLE
Calculating Importance of 'param_mix'

### ISSUE THREAD

**Issue by kiucho** [horseee/LLM-Pruner#28]
Hello. First of all, thank you for sharing great research.

I have a question about calculating the importance of parameters.

In `class TaylorImportance` in `hf_llama_pruner.py`, line 274,
1. Could you please tell me why the importance about mixed-order is calculated as follow: 
```Python
salience = salience - 0.5 * layer.weight * layer.weight.acc_grad * layer.weight
```
(not as the sum of 1st and 2nd orders)

2. Is  higher-order term neglected?

**Comment by horseee** [comment]
Hi kiucho,

* For Question 1:

The derivation of this is (e.g., for eq.5 in the paper):
<img src="https://github.com/horseee/LLM-Pruner/assets/22924514/9a5f1d5c-c64c-43c3-adcc-c45213bb86e9" alt="drawing" width="400"/>
where
<img src="https://github.com/horseee/LLM-Pruner/assets/22924514/dab0c40f-1a27-44f4-a352-e4f579b11deb" alt="drawing" width="400"/>

And thus, for here, it would be subtract the second hessian term from the first-order term.

There is a mistake in the first version of our paper and please refer to our code. We uploaded a new version of paper on arxiv (I'm not sure when it would be released, but I guess it would be available in the next 24 hours). 

* For Question2:

Yes, we can neglect higher-order terms because their impact is negligible due to their small scale compared to the preceding term. This is primarily because the first-order term always dominates, given that the model consistently remains not fully convergence when applied to our calibration samples  (evidenced by the presence of a large loss during the pruning process)

**Comment by kiucho** [comment]
Thank you for your kind explanation. I checked the new version of your paper. Thanks once again.
